### ISSUE TITLE
./deploy.sh Error

### ISSUE THREAD

**Issue by RajputAmit-17** [matwerber1/aws-alexa-smart-home-demo#1] opened 2019-12-12 12:40 UTC
(base) Area51:aws-alexa-smart-home-demo warmachine$ ./deploy.sh
Error: Unable to upload artifact lambda/layers/cfn-response/ referenced by ContentUri parameter of CloudFormationResponseLayer resource.
Parameter ContentUri of resource CloudFormationResponseLayer refers to a file or folder that does not exist /home/warmachine/Desktop/aws-alexa-smart-home-demo/lambda/layers/cfn-response

	Deploying with following values
	===============================
	Stack name                 : alexa-smart-home-demo
	Region                     : None
	Confirm changeset          : False
	Deployment s3 bucket       : None
	Capabilities               : ["CAPABILITY_IAM"]
	Parameter overrides        : {'AlexaSkillId': 'amzn1.ask.skill.d98267db-a796-4696-869a-060c3ab3c6e7', 'AlexaVendorId': 'M25E7FDW2I3AZR'}

Initiating deployment
=====================
Error: Failed to package template: /home/warmachine/Desktop/aws-alexa-smart-home-demo/packaged.yaml. 
 [Errno 2] No such file or directory: '/home/warmachine/Desktop/aws-alexa-smart-home-demo/packaged.yaml'
(base) Area51:aws-alexa-smart-home-demo warmachine$ 
@matwerber1

**Comment by matwerber1** [comment] 2019-12-17 14:52
Hi - sorry for the trouble. I will investigate today.

**Comment by matwerber1** [comment] 2019-12-17 20:20
The reason for the issue is that the custom Lambda Layers I had created were in a folder (node_modules) that is normally ignored in `.gitignore`. I've manually adding them to the project and pushed the commit. I'll test the project out today and see if I can redeploy from scratch...

Commit b4c6ecd983fd0e77653056b0a4da1f3e26dba87f

**Comment by matwerber1** [comment] 2019-12-17 21:26
I actually needed to make several additional changes... I had left out certain dependencies and build steps. It should be working now, but please test and let me know?

**Comment by matwerber1** [comment] 2019-12-18 18:15
Closing, but please re-open if you still have issues.

**Comment by RajputAmit-17** [comment] 2019-12-25 17:54
thanks, @matwerber1  cloud formation template working perfectly. unfortunately, I got an error while linking Alexa skill (error?error=redirect_mismatch&client_id)
![Screenshot (82)](https://user-images.githubusercontent.com/58136917/71449148-3443d280-276d-11ea-9219-8e00662c0599.png)

**Comment by matwerber1** [comment] 2019-12-25 20:39
Hmm - my guess is you have the wrong Cognito client ID, Alexa Vendor ID, or wrong URIs somewhere...

1. Double-check on [Step 6](https://github.com/matwerber1/aws-alexa-smart-home-demo/blob/master/docs/01-create-alexa-skill-and-aws-backend.md) that you're using the correct skill id and vendor ID. Also make sure that you're using your Alexa `Vendor ID`, not your `Customer ID`

2. Within the Alexa Developer Console on the account linking page, make sure you copy-pasted the correct values:

* Your `Authorization URI` should look like `https://999999999999-alexa-smart-home-demo-domain.auth.us-east-1.amazoncognito.com/oauth2/authorize?response_type=code&client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxredirect_uri=https://pitangui.amazon.com/api/skill/link/xxxxxxxxxxxxx&state=STATE`

* Your `Access Token URI` should look like `https://999999999999-alexa-smart-home-demo-domain.auth.us-east-1.amazoncognito.com/oauth2/token?state=STATE`

* Your `Client ID` should come from Cognito and should be a string that looks like `70c4bia7dsh8sddfoje02kfo`

Let me know if this helps? 

Also, I updated the docs with these examples.

**Comment by matwerber1** [comment] 2019-12-25 20:58
Also - if you previously linked your Amazon test account to your skill but later re-created or re-attached your skill to a new Cognito User Pool, then your user account will still be linked to the old (incorrect) Cognito pool.

To associate to the new user pool, you would need to uninstall the custom skill then re-install / re-register your test user to create the association to the new Cognito pool.

**Comment by RajputAmit-17** [comment] 2019-12-25 22:19
so I started from scratch followed the guide still got the same error message.

**Comment by matwerber1** [comment] 2019-12-25 22:49
OK I might know the issue - 

In `template.yaml`, I'm missing an ampersand when I generate the Authorization URI...

I have: 

```
AlexaAuthorizationURI:
#    Condition: UpdateResourceCondition
    Description: Used to configure Account Linking in Alexa Developer Console.
    Value: 
      Fn::Join: 
        - ''
        - - !GetAtt CognitoDomain.FullDomain
          - '/oauth2/authorize?response_type=code&client_id='
          - !Ref CognitoAlexaAppClient
          - 'redirect_uri=https://pitangui.amazon.com/api/skill/link/'
          - !Ref AlexaVendorId
```

But `- 'redirect_uri=https://pitangui.amazon.com/api/skill/link/'` should have an ampersand right before the `redirect`. In other words, it should be: 

`- '&redirect_uri=https://pitangui.amazon.com/api/skill/link/'`

I just pushed this change to the repo. 

I'm not sure why/how I'm able to sign up and use my app given this typo, but try fixing that and see if it works?

**Comment by matwerber1** [comment] 2019-12-25 22:58
Also - you should be able to just edit the URI in the Alexa skill configuration and then re-link your account to your skill. I don't think you need to redeploy anything with CloudFormation.

Example: 
![image](https://user-images.githubusercontent.com/28939541/71451264-e4dab380-2726-11ea-85e3-f48a8ac63722.png)

**Comment by RajputAmit-17** [comment] 2019-12-27 15:59
![IMG_20191227_212308](https://user-images.githubusercontent.com/58136917/71523502-5ebd9900-28ef-11ea-8a8a-e7acae0bf7b9.jpg)
Thanks for your effort and time. I successful build this awesome project.you can close the issue
@matwerber1

**Closed as completed** 2019-12-27 16:00 UTC

**Comment by matwerber1** [comment] 2019-12-27 16:08
Super cool, glad it worked and sorry for the trouble! Thank you for your feedback to make this project better :)

**Comment by kabcasa** [comment] 2020-04-14 14:02
PLS i get this error on deploy .  :
Error: Unable to upload artifact ../../lambda/layers/cfn-response referenced by                                                                       ContentUri parameter of CloudFormationResponseLayer resource.
Unable to locate credentials

        Deploying with following values
        ===============================
        Stack name                 : alexa-smart-home-demo
        Region                     : None
        Confirm changeset          : False
        Deployment s3 bucket       : None
        Capabilities               : ["CAPABILITY_IAM"]
        Parameter overrides        : {'AlexaSkillId': 'amzn1.ask.skill.27f4eb97-                                                                      e1eaxxxxxxxxxxxxxx', 'AlexaVendorId': 'xxxxxxxxxxxxxxxx'}

Initiating deployment
=====================
Error: Failed to package template: /home/pi/alexa/aws-alexa-smart-home-demo-mast                                                                      er/.aws-sam/build/packaged.yaml.
 [Errno 2] No such file or directory: '/home/pi/alexa/aws-alexa-smart-home-demo-                                                                      master/.aws-sam/build/packaged.yaml'
p

--------------------------------------
I read that was resolved but i don't understand i still get it
i checked the .aws-sam/build/VerifyCognitoTokenFunction/package.json

{
  "name": "cfprovider-uuid",
  "version": "1.0.0",
  "dependencies": {
    "https": "^1.0.0",
    "node-jose": "^1.1.3"
  }
}

**Comment by MasTerYoDa-60** [comment] 2021-12-15 11:47
Good morning Matwerbert1
His work is like an oasis in the middle of the desert: everything is very organized and complete... but not everything is flowers, and I am facing the same problem that my colleague faced in 2019: the “deploy.sh” file does not work in powershell , so I decided to run it step by step. The first part, “sam build” , works, but the second part, when we try to generate the output file (.........) presents the following error message in attached
![Captura de tela 2021-12-14 173125](https://user-images.githubusercontent.com/93381582/146180952-5709ec34-3c6a-443f-9014-3f07479759ae.png)
:

I'm sure I'm missing something, so I came to ask the creator of the work about what I can do to make the work work...

**Comment by matwerber1** [comment] 2021-12-15 16:52
Hi @MasTerYoDa-60,

SAM CLI commands like `sam package ...` are ultimately executing AWS SDK commands for you, such as `cloudformation deploy` or - as shown in your error message, `s3:PutObject`. 

This means that the SAM CLI needs AWS credentials... which, like the AWS CLI & SDK, are derived from your [local credentials files](https://docs.aws.amazon.com/sdkref/latest/guide/file-location.html), which should be`%USERPROFILE%\.aws\config` and `%USERPROFILE%\.aws\credentials` on Windows. 

Your error message of `the AWS Access Key Id you provided does not exist in our records` indicates one of three problems: 

1. You haven't configured the AWS CLI yet (run `aws configure` after installing CLI)
2. You configured the CLI, but the IAM user you specified as the default profile **{see Note 1}** in your AWS credentials/config files no longer exists
3. You configured the CLI and the IAM user exists in your CLI config files, but the specific access key you've listed no longer exists (maybe you deleted / rotated it?)

**{Note 1}** - it's possible to configure multiple AWS profiles within your CLI configuration file. the way I wrote the SAM commands `deploy.sh`, it assumes you are using the `[default]` profile from your config. If you have multiple profiles and need to use a different one, add `--profile YOUR_PROFILE` to the SAM commands.

Here are a couple links to help you debug: 

1. https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html
2. https://aws.amazon.com/premiumsupport/knowledge-center/s3-access-key-error/ (it says S3 but the troubleshooting steps are still applicable)

**Comment by MasTerYoDa-60** [comment] 2021-12-16 11:36
Thanks again for your attention, your tips were fundamental, I'd say it's already 85% working, however (there's always an "however"), an error message appears when the pile starts to form (see below):

"Error: Failed to create/update the stack: alexa-smart-home-demo, Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "ROLLBACK_COMPLETE" at least once"
![pilhas](https://user-images.githubusercontent.com/93381582/146364713-fe0c4608-7254-4f39-8120-0413c2177d7a.png)

**Comment by matwerber1** [comment] 2021-12-17 05:44
@MasTerYoDa-60, sorry that you're running intro trouble!

Your screenshot above only shows the stack's current state, but it doesn't say **why** the stack failed and rolled back. This is available on the "Events" page of the stack.

Would you please open a new issue (instead of using this one) and  provide screenshots details of *why* your stack failed?
